# Generated by Django 6.0.4 on 2026-04-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementjob',
            name='bw_image',
            field=models.ImageField(blank=True, null=True, upload_to='bw/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='measurementjob',
            name='estimated_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementjob',
            name='mockup_image',
            field=models.ImageField(blank=True, null=True, upload_to='mockups/%Y/%m/%d/'),
        ),
    ]
