# Generated by Django 6.0.4 on 2026-05-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_measurementjob_bw_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementjob',
            name='shipping_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementjob',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
