# Generated by Django 6.0.4 on 2026-04-27 16:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('width_inches', models.FloatField()),
                ('height_inches', models.FloatField(blank=True, null=True)),
                ('force_format', models.CharField(blank=True, max_length=20)),
                ('ground_truth_m', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('measured_m', models.FloatField(blank=True, null=True)),
                ('tier_result', models.CharField(blank=True, max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('tube_width_mm', models.FloatField(blank=True, null=True)),
                ('px_per_inch', models.FloatField(blank=True, null=True)),
                ('loc_low_m', models.FloatField(blank=True, null=True)),
                ('loc_high_m', models.FloatField(blank=True, null=True)),
                ('area_m', models.FloatField(blank=True, null=True)),
                ('overcount_ratio', models.FloatField(blank=True, null=True)),
                ('n_paths', models.IntegerField(blank=True, null=True)),
                ('n_straight_segs', models.IntegerField(blank=True, null=True)),
                ('n_arc_segs', models.IntegerField(blank=True, null=True)),
                ('n_freeform_segs', models.IntegerField(blank=True, null=True)),
                ('error_pct', models.FloatField(blank=True, null=True)),
                ('elapsed_s', models.FloatField(blank=True, null=True)),
                ('reasoning', models.JSONField(blank=True, default=list)),
                ('physics_ok', models.BooleanField(null=True)),
                ('input_format', models.CharField(blank=True, max_length=30)),
                ('overlay_image', models.ImageField(blank=True, null=True, upload_to='overlays/%Y/%m/%d/')),
                ('ridge_image', models.ImageField(blank=True, null=True, upload_to='ridges/%Y/%m/%d/')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
