# Generated by Django 6.0.4 on 2026-04-27 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='measurementjob',
            index=models.Index(fields=['user', 'status'], name='measurement_user_id_6c43de_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementjob',
            index=models.Index(fields=['status', 'created_at'], name='measurement_status_244526_idx'),
        ),
    ]
