# Generated by Django 6.0.4 on 2026-04-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('subscription.created', 'Subscription Created'), ('subscription.updated', 'Subscription Updated'), ('subscription.canceled', 'Subscription Canceled'), ('payment.succeeded', 'Payment Succeeded'), ('payment.failed', 'Payment Failed'), ('tier.upgraded', 'Tier Upgraded'), ('tier.downgraded', 'Tier Downgraded')], max_length=40)),
                ('stripe_event_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tier_key', models.CharField(max_length=20, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=64)),
                ('price_usd_cents', models.PositiveIntegerField(default=0)),
                ('jobs_per_month', models.PositiveIntegerField(default=0)),
                ('ml_correction', models.BooleanField(default=False)),
                ('max_width_px', models.PositiveIntegerField(default=2000)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
